work_dir: /root/CPN/graph/

# feeder
feeder: utils.feeder_triplet.Feeder
train_feeder_args:
  data_path: ./unit_test/posetrack_train_data_triplet.pickle

test_feeder_args:
  data_path: ./unit_test/posetrack_val_data_triplet.pickle

# model
model: utils.gcn_model_triplet.Model
model_args:
  in_channels: 2
  num_class: 128 # output feature dimension
  edge_importance_weighting: True
  graph_args:
    layout: 'PoseTrack'
    strategy: 'spatial'

# training
device: [0,1,2,3]
batch_size: 128
test_batch_size: 1

#optim
base_lr: 0.01
step: [40, 60, 100, 150]
num_epoch: 300
